- name: Create nginx cert dir
  file: path=/opt/nginx/certs state=directory mode=0755

- name: Create strong Diffie-Hellman group
  command: openssl dhparam -out /opt/nginx/certs/kloudsec.com.dhparam.pem 2048 creates=/opt/nginx/certs/kloudsec.com.dhparam.pem

- name: Copy SSL cert
  copy: src={{ssl_cert_path}} dest=/opt/nginx/certs/kloudsec.com.crt mode=0644

- name: Copy SSL key
  copy: src={{ssl_key_path}} dest=/opt/nginx/certs/kloudsec.com.key mode=0600

# jwilder/nginx-proxy docker image reads locally from /etc/nginx/conf.d/*;
# ensure that the below host location is properly mounted as a volume in the
# above container location.
- name: Copy nginx proxy config
  copy: src=nginx.conf dest=/opt/nginx/nginx.conf
